<img src="images/logo-2020.png" alt="frankfurt school hmi" style="width: 160px;"/>

## Tutorial on NumPy arrays
Basic mathematical functions (e.g., addition, subtraction, multiplication, division, square root) on $x \in \mathbb{R}$ operate elementwise on arrays. Recall that element-wise operations are straightforward for vectors: for vectors $\boldsymbol{a} = (a_1, a_2, \ldots, a_n)$ and $\boldsymbol{b} = (b_1, b_2, \ldots, b_n)$, element-wise addition, $\boldsymbol{a} + \boldsymbol{b}$, is simply $a_i + b_i$ for $1 \leq i \leq n$. The same is true for other element-wise arithmetic operations.  Element-wise operations generalize to $m \times n$ arrays. 

In Python, basic arithmetic operations are available both as operator overloads -- meaning for example that `+` will behave elementwise when the operands are arrays and as a normal binary operator when the operands are scalars-- or as specific methods that run in the numpy module. Below, you will see examples of each.

In [1]:
import numpy as np

In [2]:
# Create an array
A = np.arange(1,5)
A

array([1, 2, 3, 4])

In [3]:
# inspect the shape of A shape
A.shape

(4,)


## Question 1. 
What is the difference between an array whose shape is (4,) an an array whose shape is (4,1)?  

[Answer](https://stackoverflow.com/questions/16995071/numpy-array-that-is-n-1-and-n). 

In [4]:
# reshape into a 2x2 matrix 
A = A.reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [5]:
A.shape

(2, 2)

In [6]:
# create another array B
B = np.array([[7,8],[9,10]])

### Basic operations

In [7]:
# Elementwise addition; both the operator overload of + and the np.add function return the same array
# [[  8.  10.]
#  [ 12.  14.]]
print("Matrix A is:\n", A, "\n")
print("Matrix B is:\n", B, "\n")
print("The elementwise addition of A and B is:\n", np.add(A,B),"\n")
print("The elementwise addition of A and B is:\n", (A+B))

Matrix A is:
 [[1 2]
 [3 4]] 

Matrix B is:
 [[ 7  8]
 [ 9 10]] 

The elementwise addition of A and B is:
 [[ 8 10]
 [12 14]] 

The elementwise addition of A and B is:
 [[ 8 10]
 [12 14]]


In [9]:
# np.add method
print(np.add(A,B))

[[ 8 10]
 [12 14]]


In [10]:
# Elementwise subtraction; both the operator overload of - and the np.subtract function return the same array
# [[-6. -6.]
#  [-6. -6.]]
print(A-B)

[[-6 -6]
 [-6 -6]]


In [11]:
# np.subtract method
print(np.subtract(A,B))

[[-6 -6]
 [-6 -6]]


In [12]:
# Elementwise product; both the operator overload of * and the np.multiply function return the same array
# [[  7.  16.]
#  [ 27.  40.]]
print(A*B)

[[ 7 16]
 [27 40]]


In [13]:
# np.multiply method
print(np.multiply(A, B))

[[ 7 16]
 [27 40]]


In [14]:
# Elementwise division; both the operator overload of / and 
# the np.divide function return the same array
# [[ 0.14285714  0.25      ]
#  [ 0.33333333  0.4       ]]
print(A / B)

[[0.14285714 0.25      ]
 [0.33333333 0.4       ]]


In [15]:
# np.divide method
print(np.divide(A,B))

[[0.14285714 0.25      ]
 [0.33333333 0.4       ]]


In [16]:
# Elementwise square root function applied to B returns the array
# [[ 2.64575131  2.82842712]
#  [ 3.          3.16227766]]
print(np.sqrt(B))

[[2.64575131 2.82842712]
 [3.         3.16227766]]


## Matrix multiplication with np.dot
If you are unfamiliar with matrix multiplication, I recommend you watch this short [Khan Academy video series](https://www.khanacademy.org/math/precalculus/precalc-matrices/multiplying-matrices-by-matrices/v/matrix-multiplication-intro).
To compute inner products of vectors, multiply a vector by a matrix, and to multiply matricies, `np.dot` may be used either as a function or an instance method. To see how each operation works, in both function and instance-method formats, let's first instantiate two vectors (i.e., rank one arrays).

<div class="alert alert-info"><b>Tip</b>:
Tip: We are following a convention from mathematics of using lowercase letters to refer to vectors and uppercase letters to refer to matrices. In Python both are arrays, so in principle we could use any variable we like. The convention nevertheless is important for people to understand code and communicate with one another.
Since you may find it useful to consult a linear algebra textbook to understand how, exactly, these computations are carried out, we are following mathematical convention.

In programming assignments, where different types of variables are in use, we may use a longer name that includes a description of the variable's type, such as data_list or data_array.
</div>



In [17]:
# create two vectors
c = np.array([11,12])
d = np.array([21, 22])
print("The variable c stores the rank-one array", c)
print("The variable d stores the rank-one array", d)

The variable c stores the rank-one array [11 12]
The variable d stores the rank-one array [21 22]


In [18]:
# Inner product of vectors using np.dot as a function
# np.dot(c,d) yields 495
print(np.dot(c,d))

495


In [19]:
# The instance method v.dot(w) also yields 495
print(c.dot(d))

495


In [20]:
# Matrix by vector product using np.dot as a function
# np.dot(A,c) yields the rank 1 array [35., 81.]
print(np.dot(A,c))

[35 81]


In [21]:
# The instance method A.dot(c) also yields the rank 1 array [35., 81.]
print(A.dot(c))

[35 81]


In [22]:
# Matrix by matrix product.  
# np.dot(A,B) yields the rank 2 array
# [[ 25.,  28.],
#   [ 57.,  64.]]
print("The matrix product of A and B is: \n", np.dot(A,B))

The matrix product of A and B is: 
 [[25 28]
 [57 64]]


In [23]:
# The instance method A.dot(B) also yields the same rank 2 array
print(A.dot(B))

[[25 28]
 [57 64]]


Alternatively, the operator `@` can be used (since Python version 3.5) to perform matrix by matrix multiplication.  Let's check the version of python we are using.

In [24]:
from platform import python_version
print(python_version())

3.6.12


In [25]:
# The @ operator 
print("Entering A @ B yields: \n", A @ B)

Entering A @ B yields: 
 [[25 28]
 [57 64]]



<div class="alert alert-warning">
<b>Caution</b>: np.dot is not commutative, just as matrix multiplication is not commutative. In other words, changing the order of operands in np.dot generally yields different results. 
</div>
If you are uncertain why this is so, I strongly recommend for you to view the introduction to matrix multiplication video from the Khan Academy [here](https://www.khanacademy.org/math/precalculus/precalc-matrices/multiplying-matrices-by-matrices/v/matrix-multiplication-intro).

Run the next cell to confirm that `np.dot(A,B)` $\neq$ `np.dot(B,A)`.

In [26]:
# np.dot is not a commutative operation.
# for example, np.dot(B,A) yields the rank 2 array
# [[ 31.,  46.],
#  [ 39.,  58.]]
print(np.dot(B,A))

[[31 46]
 [39 58]]


## Broadcasting
Array arithmetic bumps up against an important limitation.  These operations are performed <b>element-wise</b>, meaning that the operation `c + d` is performed by adding `11` from `c` to `21` from `d`, and writing the result `32` to the first element of a one-dimensional array of length 2, and adding `12` from `c` to `22` from `d` and storing the value `34` to the second element of this array: Consider again the arrays `c` and `d`:

In [27]:
c + d

array([32, 34])

## Question 2. 
What would you expect to happen if `c` and `d` were different sizes? 

A reasonable answer would be to suppose that the operation would fail and return an error, since not every element in one array would have a corresponding element in the other to execute the element-wise operation.  However, there is a built-in workaround in Python to perform arithmetic on <i>some </i> arrays of differents sizes.  This is a great feature, but can be a source of confusion if you do not understand how this workaround operates.   

Array [broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html) refers to a NumPy method for performing arithmetical operations on arrays of different shapes.  Informally, and subject to some constraints, when arrays are mismatched in shape, the smaller array is replicated or "<b>broadcast</b>" across the larger array so that they have compatible shapes to perform the arithmetical operation.

For example, suppose you wished to multiply a 1-dimensional array with 3 values, `a`, by a scalar, `b`.


In [28]:
# 3x1 array
a = np.array([11,12, 13])

# inspect the shape of a
a.shape

(3,)

In [29]:
# scalar
b = 2

The array `a` and the scalar `b` clearly do not have the same dimension.  (In fact, in this case, they aren't even the same data type.)  Without a trick like broadcasting, we would expect an element-wise operation like array-multiplication result in an error:

<img src="images/broadcasting_1a.png" alt="broadcasting_example" style="width: 380px;"/>

Broadcasting <b>stretches</b> `b` into an array of the "right" dimension for the multiplication to work. We will come back to explain what the "right" dimension amounts to, and the conditions necessary for broadcasting to work.


<img src="images/broadcasting_1b.png" alt="broadcasting_example" style="width: 450px;"/>

And we see this result, below.


In [30]:
# a * b 
# note that b is broadcasted automatically
a * b

array([22, 24, 26])

Since broadcasting is built into NumPy, it can be confusing when broadcasting errors appear.  Fortunately, the <b>General Rules for Broadcasting</b> two NumPy arrays are simple. After comparing the shape of the two arrays element-wise, two dimensions are compatible when either:

 - they are equal, or
 - one of the two dimensions is 1.
 
If these conditions are not met, then the `ValueError: opperands could not be broadcast together` exception is raised, which indicates that the size of the arrays have incompatible shapes.

Here is another broadcasting example involving a 2-dimensional array, `X`, and a 1-dimensional array, `y`.  

In [31]:
# 4x3 array
X = np.array([[1,2,3],[11, 12, 13], [21, 22, 23], [31, 32, 33]])

# inspect the shape of X
X.shape

(4, 3)

In [32]:
# 3 x 1 array
y = np.array([0,1,2])

# inspect the shape of y
y.shape

(3,)

In [33]:
X*y

array([[ 0,  2,  6],
       [ 0, 12, 26],
       [ 0, 22, 46],
       [ 0, 32, 66]])

To execute `X*y`, the 3x1 array `y` is stretched to a 4x3 array: 

<img src="images/broadcasting_2a.png" alt="broadcasting_example" style="width: 450px;"/>

In general, a 2-dimensional array multiplied by a 1-dimensional array is successfully broadcasted if the number of 1-dimensional array elements matches the number of 2-dimensional columns.  

Two illustrate what happens when the number of 1d elements does not equal the number of 2d columns, consider multiplying the 4x3 array `X` by a 4x1 array `z`.

In [34]:
# 4 x 1 array
z = np.array([0,1,2,3])

# inspect the shape of y
z.shape

(4,)

In [35]:
# mismatch in dimension, returns a ValueError
X * z

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

We may visualize this error as follows:
<img src="images/broadcasting_3.png" alt="broadcasting_example" style="width: 450px;"/>



## Example 1
Let's consider the column vectors $c$ and $d$. Observe that

$$c \cdot d \ = \ \sum_{i=1}^{n} c_i d_i \ = \ c^{T}d \ = \ 495\\ $$


where $n$ is the length of the vectors $c$ and $d$ and $c^Td$ is $c$ transpose multiplied by $d$. 

In the present case $n = 2$. But, to make this a stand alone example (in case you haven't run the code above), we have

~~~python 
c = np.array([11, 12])
d = np.array([21, 22])
~~~

One way to compute $c \cdot d$ is with a for loop, like so:

~~~python
ans = 0
for c,d in zip(c,d):
    ans += c*d
ans
~~~
For this course, however, you <b>should not</b> use for loops but instead <b>vectorize</b> your code whenever possible. For loops are computationally expensive and do no scale well to large, multi-feature data sets. This is not a trivial point: vectorization can make the difference between solving a problem and not solving it.  It is the primary reason you studied linear algebra in your first term.

Note that in Python, 

~~~python
c * d
~~~
returns an np.array rather than the scalar value 495.  (Try it, if you don't see why.)  However, we could write

~~~python
np.sum(a*b)
~~~
which sums the elements of `array([321,264])` to return the scalar 495.  The `np.sum` function is a Python <i>instance method</i>, so an alternative way to do this is 

~~~python
(c*d).sum()
~~~

Although these techniques are useful, particularly in the early stages of thinking through how to implement a solution and using methods and functions that closely align to your reasoning, a more convenient way to compute $c \cdot d$  from a coding perspective is

~~~python
np.dot(c,d)
~~~

The function `np.dot()` is also an instance method, so an alternative way to do this is

~~~python
(c).dot(d)
~~~

## Question 3.

Is `(d).dot(c)` equivalent to `(c).dot(d)`? Check!


In [37]:
# Question 3
c.dot(d)

495

## Example 2 (advanced)
An alternative way to compute $c \cdot d$, when both $c$ and $d$ are <b>normed vectors</b>, is

$$ c \cdot d = \Vert c \Vert \Vert d \Vert \cos \theta_{cd} $$

which is the <i>magnitude</i> of $c$, written $\Vert c \Vert$, times the <i>magnitude</i> of $d$, times the cosine of the angle $\theta$ between $c$ and $d$.  Often the angle is unknown, so this expression is rearranged to facilitate finding $\theta$ by solving first for $\cos \theta$:

$$ \cos \theta_{cd} = \frac{c^Td}{\Vert c \Vert \Vert d \Vert} $$

The magnitude of a vector is its length with respect to a norm but not every vector is a normed vector. The <i>Euclidean norm</i> is the most common norm, but not the only one. A Euclidean vector of length $n$ picks a single point in $n$-dimensional Euclidean space. For example, the vector $c$, evaluated with respect to the Euclidean norm, would determine the point (11, 12) on the Euclidean plane $\mathbb{R}^2$.

Let's suppose $\Vert \cdot \Vert$ is the Euclidean norm, which is written as $\Vert \cdot \Vert_2$ and also called the $L^2$-norm.  The <b>Euclidean norm</b> of a vector $\boldsymbol{v} \in \mathbb{R}^n$ is

$$  \Vert \boldsymbol{v} \Vert_2 = \sqrt{v^2_1 + v^2_2 + \cdots + v^2_n} $$

Equivalently, the Euclidean norm of $\boldsymbol{v}$ may be expressed as the square root of the inner produce of $\boldsymbol{v}$ and itself:

$$ \Vert \boldsymbol{v} \Vert_2 = \sqrt{\boldsymbol{v}^T\boldsymbol{v}} $$

#### How to compute an answer:

As part of the Python linear algebra module, we can compute the Euclidean length of $\boldsymbol{v}$ by using

~~~python
v_mag = np.linalg.norm(v)
~~~
Then, we may calculate the cosine of the angle $\theta$ between $c$ and $d$ by

~~~python
cos_theta = np.dot(c,d) / (np.linalg.norm(c) * np.linalg.norm(d))
~~~

The angle $\theta$ (in gradians) then is calculated by

~~~python
angle_theta = np.arccos(cos_theta)
~~~

We may calculate $c \cdot d$, of course, by 

~~~python
np.linalg.norm(c) * np.linalg.norm(d) * cos_theta
~~~

For more information about numpy mathematical operations, visit this [SciPy.org](https://docs.scipy.org/doc/numpy/reference/routines.math.html) reference page.

---
<i> This is an ungraded tutorial.</i>